name: 31_call-automatic-github-rebase-dev

on:
  push:
    branches:
      - 1-QA

jobs:
  github-rebase-qa:
    uses: CentralGP/github-workflows/.github/workflows/30_reuse-rebase-qa.yaml@master
    with:
      PARENT_BRANCH: '1-QA'
      CHILD_BRANCH: '0-DEV'
      ACTOR: 'automatic-rebase'
    secrets:
      SNAPLOGIC_REPO_CREATION_PAT: ${{ secrets.SNAPLOGIC_REPO_CREATION_PAT }}